dev_addr: 127.0.0.1:8080
strict: true
site_name: Meteor
site_dir: site
docs_dir: docs
repo_url: https://github.com/srault95/meteor-app-base
site_url: http://srault95.github.io/meteor-app-base
repo_name: GitHub
site_description: Documentations Meteor
site_author: Stéphane RAULT
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_branch: gh-pages
remote_name: gh-pages
theme: readthedocs
pages:
    - 'Accueil': index.md
    - 'Structure de Projet': project-structure.md
    - 'Tests Meteor': tests.md
    - 'Plugins':
        - "Iron Router": iron-router.md
        - "Simple Schema": simple-schema.md
        - "Templates": templating.md
        - "Authentification Sociale": social-auth.md
        - "autoform-semantic-ui": autoform-semantic-ui.md
        - "useraccounts": useraccounts.md
        - "collection-timestampable": collection-timestampable.md
        - "collection-softremovable": collection-softremovable.md
        - "meteor-collection-helpers": meteor-collection-helpers.md
        - "meteor-roles": useraccounts-roles.md
        - "API Rest": rest-api.md
        - "Internationalisation": tap-i18n.md
        - "publish-counts": publish-counts.md
        - "Sécurité": sikka.md
        - "En cours d'évaluation": plugins-a-etudier.md
    - 'MongoDB': mongodb.md
    - 'Mails': email.md
    - 'Applications':
      - 'E-Commerce': app-reactioncommerce.md
      - 'CMS': app-orionjs.md
      - 'Site Communautaire': app-telescope.md
    - 'Liens': links.md
    - 'Tips': tips.md
    - 'Faq': faq.md
